config/routes.rb
Rails.application.routes.draw do
  scope "/#{(Spree::Config[:blog_title] || 'blog').to_url}" do
    match '/tagged/:tag',           :to => 'posts#index', :as => 'posts_by_tag'
    match '/:year(/:month(/:day))', :to => 'posts#index', :as => 'posts_by_date', 
                                                            :year  => /\d{4}/,
                                                            :month => /\d{1,2}/,
                                                            :day   => /\d{1,2}/
    resources :posts, :path => '/' do
      resources :comments
    end
  end

  namespace :admin do 
    resources :posts do
      resources :comments
      resources :images, :controller => 'post_images'
    end
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  before_save :check_approved
  before_save :check_user, :if => :user

  attr_accessible :name, :email, :message, :url

  validates_presence_of :message, :post_id, :name
  validates_length_of   :message, :maximum => 1000
  validates_presence_of :email,   :unless => :user
  validates_format_of   :email,   :with => /\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i
  validates_format_of   :url,     :with => /http\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?/, :allow_blank => true

  default_scope order('approved, approved_on DESC')
  scope :approved, where(:approved => true)

  def status
    approved ? "approved" : "not approved"
  end

private
  def check_user
    self.email = user.email
  end

  def check_approved
    return unless approved_changed?
    self.approved_on = approved ? Date.today : nil
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  make_permalink
  acts_as_taggable
  validates_presence_of :title
  has_many :images, :as => :viewable, :order => :position, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  before_save :check_published

  default_scope includes(:tags).order('publish, published_on DESC')
  scope :published, where(:publish => true)

  def self.by_date(year, month=nil, day=nil) 
    start_date = Date.new(year, month || 1, day || 1)
    end_date = nil

    if day 
      end_date = start_date.advance(:days   => 1)
    elsif month
      end_date = start_date.advance(:months => 1)
    else
      end_date = start_date.advance(:years  => 1)
    end

    where('published_on BETWEEN ? AND ?', start_date, end_date)
  end

  def self.group_dates
    select('published_on, title, permalink').
      group_by {|post| post.published_on.to_date.advance(:days => -(post.published_on.day-1)) }.
      group_by {|date| date.first.year }
  end

  def status
    publish ? "published" : "unpublished"
  end

  def to_param
    return permalink unless permalink.blank?
    title.to_url
  end 

private
  def check_published
    return unless publish_changed?
    self.published_on = publish ? Date.today : nil
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  resource_controller

  helper 'spree/base'

  update.response do |format|
    format.html { redirect_to admin_comments_path }
  end
  create.response do |format|
    format.html { redirect_to edit_admin_comments_path(@comments) }
  end
private
  def collection
    return @collection if @collection

    @collection = Comment
    if params[:post_id]
      @post = Post.find_by_permalink(params[:post_id])
      @collection = @post.comments
    end

    @collection = @collection.paginate(:page => params[:page], :per_page => 10)
  end

  def object
    return @object if @object

    @object = Comment.find_by_id(params[:id])
    @object.approved = params[:comment][:approved] if params[:comment] && params[:comment].key?(:approved)
    @object
  end
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < Admin::BaseController
  resource_controller
  belongs_to :post

  new_action.response do |wants|
    wants.html {render :action => :new, :layout => false}
  end

  create.response do |wants|
    wants.html {redirect_to admin_post_images_url(@post)}
  end

  update.response do |wants|
    wants.html {redirect_to admin_post_images_url(@post)}
  end

  create.before :set_viewable
  update.before :set_viewable
  destroy.before :destroy_before

  destroy.response do |wants|
    wants.html do
      render :text => ""
    end
  end


private
  def parent_object
    @parent_object ||= Post.find_by_permalink(params[:post_id])
  end

  def object
    @object ||= end_of_association_chain.find(params[:id])
    @image = @object
  end

  def model_name
    'image'
  end

  def object_name
    'image'
  end

  def set_viewable
    object.viewable = @post
  end

  def destroy_before
    @viewable = object.viewable
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  resource_controller

  helper 'spree/base'

  new_action.response do |format|
    format.html {render :action => :new, :layout => false}
  end
  update.response do |format|
    format.html { redirect_to admin_posts_path }
  end
  create.response do |format|
    format.html { redirect_to edit_admin_posts_path(@posts) }
  end
private
  def collection
    @collection ||= Post.paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/comments_controller.rb
class CommentsController < Spree::BaseController
  before_filter :load_post, :only => [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(params[:comment])
    @comment.user = current_user
    if @comment.save
      flash[:notice] = I18n.t(:created_successfully_pending_approval)
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

private
  def load_post
    @post = Post.find_by_permalink(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < Spree::BaseController
  before_filter :load_tag_cloud, :load_dates

  def index
    @tag   = params[:tag]
    @year  = params[:year]
    @month = params[:month]
    @day   = params[:day]

    @posts = @year ? Post.by_date(@year.to_i, @month.try(:to_i), @day.try(:to_i)) : Post
    @posts = @posts.published
    @posts = @posts.tagged_with(@tag) if @tag

    respond_to do |format|
      format.html { @posts = @posts.paginate(:page => params[:page], :per_page => 10) }
      format.rss
    end
  end

  def show
    @post = Post.published.find_by_permalink(params[:id])
  end

protected
  def load_tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end

  def load_dates
    @dates = Post.group_dates
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper

  def make_title(tag=nil, year=nil, month=nil, day=nil)
    if tag
      t("posts_tagged") % tag.humanize.capitalize
    elsif year
      if day
        t("posts_day") % Date.new(year.to_i,month.to_i,day.to_i).strftime("%A, %d %B, %Y")
      elsif month
        t("posts_month") % Date.new(year.to_i,month.to_i,1).strftime("%B %Y")
      else
        t("posts_year") % year.to_s
      end
    else
      Spree::Config[:blog_title] || t("blog")
    end
  end
end

app/views/admin/comments/_form.html.erb
<%= render "shared/error_messages", :target => f.object %>
<fieldset>
    <%= f.field_container :name do %>
        <%= f.label :name, t("name") %> <span class="required">*</span><br />
        <%= f.text_field :name, :class => 'fullwidth name'  %>  
        <%= f.error_message_on :name %>
    <% end %>
    <%= f.field_container :email do %>
        <%= f.label :email, t("email") %> <span class="required">*</span><br />
        <%= f.text_field :email, :class => 'fullwidth'  %>  
        <%= f.error_message_on :email %>
    <% end %>
    <%= f.field_container :url do %>
        <%= f.label :url, t("url") %> <span class="required">*</span><br />
        <%= f.text_field :url, :class => 'fullwidth'  %>  
        <%= f.error_message_on :url %>
    <% end %>
    <%= f.field_container :message do %>
        <%= f.label :message, t("message") %><span class="required">*</span><br />
        <%= f.text_area :message, :class => 'fullwidth editor'  %>  
        <%= f.error_message_on :message %>
    <% end %>
    <%= f.field_container :approved do %>
        <%= f.check_box :approved  %>  
        <%= f.label :approved, t("approved") %>
        <%= f.error_message_on :approved %>
    <% end %>
</fieldset>

app/views/admin/comments/edit.html.erb
<%= render 'shared/blog_sub_menu' %>

<h1><%= t('editing_comment') %></h1>

<%= form_for @comment, :url => object_path do |f| %>
  <%= render 'form', :f => f %>
  <%= render :partial => 'admin/shared/edit_resource_links' %>
<% end %>

app/views/admin/comments/index.html.erb
<%= render 'shared/blog_sub_menu' %>

<h1><%= @post ? "#{t("comments_for")} \"#{@post.title}\"" : t("comments") %></h1>
<table class="index">
  <thead>
    <%= hook :admin_comments_index_headers do %>
      <% unless @post %>
        <th width="100px"><%= t("post") %></td>
      <% end %>
      <th><%= t("name") %></td>
      <th><%= t("email") %></td>
      <th><%= t("url") %></td>
      <th><%= t("message") %></td>
      <th width="80px"><%= t("status") %></td>
    <% end %>
    <th width="100px">
      <%= hook :admin_comments_header_actions %>
    </th>
  </tr>
  <thead>
<% @comments.each do |comment| %>
  <tr id="<%= dom_id comment %>"> 
    <%- locals = {:comment => comment} %>
    <%= hook :admin_comments_index_rows, locals do %>
      <% unless @post %>
        <td><%= link_to comment.post.title, edit_admin_post_path(comment.post) %></td>
      <% end %>
      <td><%= comment.name %></td>
      <td><%= comment.email %></td>
      <td><%= link_to(comment.url, comment.url) unless comment.url.blank? %></td>
      <td><%= markdown comment.message %></td>
      <td><%= comment.approved ? link_to(t(comment.status), post_path(comment.post), :target => comment.post.permalink) : t(comment.status) %></td>
    <% end %>
    <td class="actions">
      <%= hook :admin_comments_index_row_actions, locals do %>
        <%= link_to_edit comment %>&nbsp;
        <%= link_to_delete comment %>
      <% end %>
    </td>
  </tr>
<% end %> 
  </tbody>
</table>
<%= will_paginate(:previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>

app/views/admin/post_images/_form.html.erb
<tr>
  <td><%= t("filename") %>:</td>
  <td><%= f.file_field :attachment %></td>
</tr>
<tr>
  <td><%= t("alt_text") %>:</td>
  <td><%= f.text_area :alt %></td>
</tr>

app/views/admin/post_images/edit.html.erb
<%= render :partial => 'shared/blog_sub_menu' %>

<%= render :partial => 'shared/blog_tabs', :locals => {:current => "Images"} %>

<%= form_for(:image, :url => admin_post_image_url(@post), :html => { :method => :put, :multipart => true }) do |f| %>
  <%= render "shared/error_messages", :target => @image %>
  <table class="basic-table">
    <tr>
      <td><%= t("thumbnail") %>:</td>
      <td><%= link_to(image_tag(@image.attachment.url(:mini)), @image.attachment.url(:post)) %></td>
    </tr>
    <%= render :partial => "form", :locals => { :f => f } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), admin_post_images_url(@post), :id => "cancel_link" %>
  </p>
<% end %>

app/views/admin/post_images/index.html.erb
<%= render :partial => 'shared/blog_sub_menu' %>

<%= render :partial => 'shared/blog_tabs', :locals => {:current => "Images"} %>

<table class="index">
  <tr>
    <th><%= t("thumbnail") %></th>
    <th><%= t("alt_text") %></th>
    <th><%= t("action") %></th>
  </tr>

  <% @parent_object.images.each do |image| %>
    <tr id="<%= dom_id(image) %>">
      <td><%= link_to(image_tag(image.attachment.url(:mini)), image.attachment.url(:product)) %></td>
      <td><%= image.alt %></td>
      <td class="actions">
        <%= link_to_with_icon('edit', t("edit"), edit_admin_post_image_url(@post, image)) %>
        &nbsp;
        <%= link_to_delete image, {:url => admin_post_image_url(@post, image) }%>
      </td>
    </tr>
  <% end %>

</table>

<div id="images"></div>
<br/>
<p>
    <%= link_to icon('add') + ' ' + t("new_image"), new_admin_post_image_url(@post), :id => "new_image_link" %>
</p>

<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){

      jQuery('#new_image_link').click(function (event) {
        event.preventDefault();
        jQuery(this).hide();
        jQuery.ajax({type: 'GET', url: this.href, data: ({authenticity_token: AUTH_TOKEN}), success: function(r){ jQuery('#images').html(r);} });
      });

    });
  </script>
<% end %>

app/views/admin/post_images/new.html.erb
<h4><%= t("new_image") %></h4>
<%= form_for(:image, :url => admin_post_images_path(@post), :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render :partial => "form", :locals => { :f => form } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>


<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_image_link').show();
    jQuery('#images').html('');
  });  
 
</script>

 
 

app/views/admin/posts/_form.html.erb
<%= render "shared/error_messages", :target => f.object %>

<div id="images" style="display:none">
  <% f.object.images.each do |image| %>
    <%= image_tag image.attachment.url(:large), :alt => image.alt %>
  <% end %>
</div>

<fieldset>
    <%= f.field_container :title do %>
        <%= f.label :title, t("title") %> <span class="required">*</span><br />
        <%= f.text_field :title, :class => 'fullwidth title'  %>  
        <%= f.error_message_on :title %>
    <% end %>
    <%= f.field_container :tag_list do %>
      <%= f.label :tag_list, t("tags") %> <span class="small"><%= t("comma_seperated") %><span>
        <%= f.text_field :tag_list, :class => 'fullwidth'  %>  
        <%= f.error_message_on :tags %>
    <% end %>
    <%= f.field_container :body do %>
        <%= f.label :body, t("body") %>
        <%= f.text_area :body, :class => 'fullwidth editor'  %>  
        <%= f.error_message_on :body %>
    <% end %>
    <%= f.field_container :publish do %>
        <%= f.check_box :publish  %>  
        <%= f.label :publish, t("publish") %>
        <%= f.error_message_on :publish %>
    <% end %>
    <h2><%= t("metadata") %></h2>
    <p> 
      <%= f.label :meta_keywords, t("meta_keywords")%><br />
      <%= f.text_field :meta_keywords, :class => 'fullwidth' %>
    </p>
    <p> 
      <%= f.label :meta_description, t("meta_description")%><br />
      <%= f.text_field :meta_description, :class => 'fullwidth' %>
    </p>
</fieldset>

app/views/admin/posts/edit.html.erb
<%= render 'shared/blog_sub_menu' %>

<%= form_for @post, :url => object_path do |f| %>
  <%= render 'form', :f => f %>
  <%= render :partial => 'admin/shared/edit_resource_links' %>
<% end %>

app/views/admin/posts/index.html.erb
<%= render 'shared/blog_sub_menu' %>

<div class='toolbar'>
    <ul class='actions'>
      <li id="new_post_link">
        <%= button_link_to t("new_post"), 
                         new_object_url, 
                         {:remote => :true, :icon => 'add' } %>
      </li> 
    </ul>
  <br class='clear' />
</div>
<div id="new_post"></div>

<h1><%= t("posts") %></h1>
<table class="index">
  <thead>
    <%= hook :admin_posts_index_headers do %>
      <th><%= t("title") %></td>
      <th><%= t("status") %></td>
    <% end %>
    <th>
      <%= hook :admin_posts_header_actions %>
    </th>
  </tr>
  <thead>
<% @posts.each do |post| %>
  <tr id="<%= dom_id post %>"> 
    <%- locals = {:post => post} %>
    <%= hook :admin_posts_index_rows, locals do %>
      <td><%= link_to post.title, edit_admin_post_path(post) %></td>
      <td>
        <% if post.publish %> 
          <%= link_to(t(post.status), post_path(post), :target => post.permalink) %>
          <br/>
          <%= time_ago_in_words post.published_on %> ago
        <% else %>
          <%= t(post.status) %>
        <% end %>
      </td>
    <% end %>
    <td class="actions">
      <%= hook :admin_posts_index_row_actions, locals do %>
        <%= link_to_edit post %>&nbsp;
        <%= link_to_delete post %>
      <% end %>
    </td>
  </tr>
<% end %> 
  </tbody>
</table>
<%= will_paginate(:previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>

app/views/admin/posts/new.html.erb
<%= render 'shared/blog_sub_menu' %>

<%= form_for @post, :url => collection_path do |f| %>
  <%= render 'form', :f => f %>
  <%= render :partial => 'admin/shared/new_resource_links' %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for comment, :url => post_comments_path(post) do |f| %>
  <%= render "shared/error_messages", :target => f.object %>
  <p>
    <%= f.label :name, t('your_name') %><span class="required">*</span>
    <br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email, t('your_email') %><span class="required">*</span> 
    <br/>
    <% if current_user %>
      <%= current_user.email %>
    <% else %>
      <%= f.text_field :email %>
    <% end %>
    <br/>
    <span class="small"><%= t('not_shared') %></span>
  </p>
  <p>
    <%= f.label :url, t('your_website') %>
    <br/>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :message, t('message') %> <span class="required">*</span>
    <br/>
    <%= f.text_area :message %>
  </p>
  <%= f.submit t('post_comment'), :class=>'button' %>
<% end %>

app/views/comments/new.html.erb
<h1><%= t('commenting_on') % @post.title %></h1>

<%= render 'form', :comment => @comment, :post => @post %>

app/views/posts/_sidebar.html.erb
<h2><%= t('blog_archive') %></h2>
<div id="blog-archive">
  <ul class="years">
    <% @dates.each do |year, months| %>
      <li>
      <span><%= year %></span>
      <ul class="months">
        <% months.each do |month, posts| %>
          <li><span><%= month.strftime('%B') %></span>
          <ul class="posts">
            <% posts.each do |post| %>
              <li><%= link_to post.title, post_path(post) %></li>
            <% end %>
          </ul>
          </li>
        <% end %>
      </ul>
      </li>
    <% end %>
  </ul>
</div>

<%= javascript_tag do %>
  $('#blog-archive')
  .find('ul:not(.years)')
    .slideUp()
    .end()
  .find('span').click(function() {
    $(this).find('+ul').slideToggle('slow');
  });
<% end %>

<h2><%= t('tags') %></h2>
<%= render 'tag_cloud' %>

app/views/posts/_tag_cloud.html.erb
<div class="tag-cloud">
  <% tag_cloud(@tags, %w(tag1 tag2 tag3 tag4)) do |tag, css_class| %>
    <%= link_to tag.name, posts_by_tag_path(tag.name), :class => css_class %>
  <% end %>
</div>

app/views/posts/_tags.html.erb
<%= t("tags") %> <%= tags.collect do |tag| 
  link_to(tag.name, posts_by_tag_path(tag.name))
end.join(', ').html_safe %>

app/views/posts/index.html.erb
<% self.title = make_title(@tag, @year, @month, @day) %>

<% content_for(:head) do %>
  <%= stylesheet_link_tag 'blog' %>
<% end %>
<% content_for(:sidebar) do %>
  <%= render 'sidebar' %>
<% end %>

<div id="posts">
  <h1><%= make_title(@tag, @year, @month, @day) %></h1>

  <% @posts.each do |post| %>
    <div class="post">
      <span class="date"> <%= post.published_on.to_date.strftime '%A, %B %d, %Y' %> </span>
      <h2><%= link_to post.title, post_path(post) %></h2>
      <div class="body">
        <%= markdown post.body %>
      </div>
      <div class="info">
        Posted <%= time_ago_in_words post.published_on %> ago
        <%= link_to t("comments"), "#{post_path(post)}#comments" %>
        <br/>
        <%= render 'tags', :tags => post.tags %>
      </div>
      <hr/>
    </div>
  <% end %>
  <%= will_paginate(@posts,
                       :previous_label => "&#171; #{t('previous')}",
                       :next_label => "#{t('next')} &#187;") %>
</div>

app/views/posts/show.html.erb
<% self.title = @post.title %>
<% def self.object; @post; end %>

<% content_for(:head) do %>
  <%= stylesheet_link_tag 'blog' %>
<% end %>
<% content_for(:sidebar) do %>
  <%= render 'sidebar' %>
<% end %>

<div id="post">
  <div class="date"><%= @post.published_on.to_date.strftime '%A, %B %d, %Y' %></div>
  <h1><%= @post.title %></h1>
  <div id="body">
    <%= markdown @post.body %>
  </div>
  <div id="tags">
    <%= render 'tags', :tags => @post.tags %>
  </div>
  <div id="date">
    Posted <%= time_ago_in_words @post.published_on %> ago
  </div>

  <div id="comments">
    <h2><%= t("comments") %></h2>
    <% @post.comments.approved.each do |comment| %>
      <div class="comment">
        <p class="info">
        Posted by <b><%= comment.url.blank? ? comment.name : link_to(comment.name, comment.url) %></b> <%= time_ago_in_words comment.created_at %> ago
        </p>
        <div>
        <%= markdown comment.message %>
        </div>
        <hr/>
      </div>
    <% end %>
    <div id="new-comment">
      <p><%= t('comment_on_post') %></p>

      <%= render 'comments/form', :comment => @post.comments.new, :post => @post %>
    </div>
  </div>
</div>

app/views/shared/_blog_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav">
    <%= hook :admin_blog_sub_tabs do %>
      <%= tab :posts, :match_path => '/posts' %>
      <%= tab :comments, :match_path => '/comments' %>
    <% end %>
  </ul>
<% end %>

app/views/shared/_blog_tabs.html.erb
<h1><%= raw(t("editing_post") + " &ldquo;#{@post.title}&rdquo;") %></h1>

<% content_for :sidebar do %>

  <h3><%= @post.title %></h3>
  <br class="clear" />

  <ul class="sidebar post-menu">
    <%= hook :admin_post_tabs, {:current => current} do %>

      <li<%= raw(' class="active"') if current == "Post" %>>
      <%= link_to t("post"), edit_admin_post_path(@post) %>
      </li>
      <li<%= raw(' class="active"') if current == "Images" %>>
      <%= link_to "#{t("images")} (#{@post.images.count})", admin_post_images_path(@post) %>
      </li>
      <li<%= raw(' class="active"') if current == "Comments" %>>
      <%= link_to "#{t("comments")} (#{@post.comments.count})",  admin_post_comments_path(@post)  %>
      </li>
    <% end %>
  </ul>
  <br class="clear" />

<% end %>